name: cloud-native-starter-spring

services:
  articles-service:
    build: ./articles-service
    container_name: cns-articles-service
    hostname: articles-service
    networks:
      - cns-net

  authors-service:
    build: ./authors-service
    container_name: cns-authors-service
    hostname: authors-service
    networks:
      - cns-net

  web-api-service:
    build: ./web-api-service
    container_name: cns-web-api-service
    hostname: web-api-service
    environment:
      ARTICLES_SERVICE_URL: http://articles-service:9080/articles/v1/
      AUTHORS_SERVICE_URL: http://authors-service:9080/api/v1/
    depends_on:
      - articles-service
      - authors-service
    networks:
      - cns-net

  nginx:
    build: ./nginx
    container_name: cns-nginx
    hostname: cns-nginx
    ports:
      - "8080:80"
    depends_on:
      - articles-service
      - authors-service
      - web-api-service
    networks:
      - cns-net

networks:
  cns-net:
    driver: bridge
