worker_processes auto;

events {
  worker_connections 1024;
}

http {
  upstream articlesservices {
    server articles-service:9080;
    keepalive 100;
  }
  upstream authorsservices {
    server authors-service:9080;
    keepalive 100;
  }
  upstream webapiservices {
    server web-api-service:9080;
    keepalive 100;
  }

  server {
    listen 80;

    location /articles/ {
      proxy_pass http://articlesservices/articles/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /authors/ {
      proxy_pass http://authorsservices/api/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /web-api/ {
      proxy_pass http://webapiservices/web-api/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}
