worker_processes auto;

events {
  worker_connections 1024;
}

http {
  upstream mainservices {
    server main-service:9080;
    keepalive 100;
  }
  upstream authservices {
    server auth-service:9080;
    keepalive 100;
  }
  upstream bookingservices {
    server booking-service:9080;
    keepalive 100;
  }
  upstream customerservices {
    server customer-service:9080;
    keepalive 100;
  }
  upstream flightservices {
    server flight-service:9080;
    keepalive 100;
  }

  server {
    listen 80;

    location /acmeair/ {
      proxy_pass http://mainservices/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /auth/ {
      proxy_pass http://authservices/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /booking/ {
      proxy_pass http://bookingservices/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /customer/ {
      proxy_pass http://customerservices/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /flight/ {
      proxy_pass http://flightservices/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}
