customer.service=${CUSTOMER_SERVICE:localhost:9080/customer}
flight.service=${FLIGHT_SERVICE:localhost:9080/flight}
mongo.host=${MONGO_HOST:localhost}
mongo.port=${MONGO_PORT:27017}
mongo.dbname=${MONGO_DBNAME:}
mongo.user.passwd=${MONGO_DBUSER_PASSWD:}
mongo.options=${MONGO_OPTIONS:}
secure.service.calls=${SECURE_SERVICE_CALLS:true}
secure.user.calls=${SECURE_USER_CALLS:true}
track.reward.miles=${TRACK_REWARD_MILES:true}
