worker_processes auto;

events {
  worker_connections 1024;
}

http {
  upstream customersservice {
    server customers-service:9080;
    keepalive 100;
  }
  upstream vetsservice {
    server vets-service:9080;
    keepalive 100;
  }
  upstream visitsservice {
    server visits-service:9080;
    keepalive 100;
  }
  upstream apigateway {
    server api-gateway:9080;
    keepalive 100;
  }

  server {
    listen 80;

    location /customers/ {
      proxy_pass http://customersservice/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /vets {
      proxy_pass http://vetsservice/vets;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /visits/ {
      proxy_pass http://visitsservice/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    location /api/ {
      proxy_pass http://apigateway/api/;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}
