name: petclinic-quarkus

services:
  customers-service:
    build:
      context: .
      dockerfile: customers-service/Dockerfile
    container_name: pc-customers-service-q
    hostname: customers-service
    networks:
      - pc-net

  vets-service:
    build:
      context: .
      dockerfile: vets-service/Dockerfile
    container_name: pc-vets-service-q
    hostname: vets-service
    networks:
      - pc-net

  visits-service:
    build:
      context: .
      dockerfile: visits-service/Dockerfile
    container_name: pc-visits-service-q
    hostname: visits-service
    networks:
      - pc-net

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: pc-api-gateway-q
    hostname: api-gateway
    environment:
      CUSTOMERS_SERVICE_URL: http://customers-service:9080
      VISITS_SERVICE_URL: http://visits-service:9080
    depends_on:
      - customers-service
      - visits-service
    networks:
      - pc-net

  nginx:
    build: ./nginx
    container_name: pc-nginx-q
    hostname: pc-nginx-q
    ports:
      - "8080:80"
    depends_on:
      - customers-service
      - vets-service
      - visits-service
      - api-gateway
    networks:
      - pc-net

networks:
  pc-net:
    driver: bridge
