quarkus.http.port=2443

daytrader.services.gateway=${DAYTRADER_GATEWAY_SERVICE:http://localhost:2443}
daytrader.services.account=${DAYTRADER_ACCOUNTS_SERVICE:http://localhost:1443}
daytrader.services.portfolios=${DAYTRADER_PORTFOLIOS_SERVICE:http://localhost:3443}
daytrader.services.quotes=${DAYTRADER_QUOTES_SERVICE:http://localhost:4443}

quarkus.smallrye-health.root-path=/q/health
